### ISSUE TITLE
Errors in KDE

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#382]
At the moment the 3DS, Wii and GameCube games, when opening the properties tab, Rom-properties does not appear, but a tab that says xattrs. Besides not showing the thumbnails (which were successfully downloaded).

I'm currently using Manjaro KDE (Plasma 5.27.6 - Framework 5.107.0)

![Screenshot_20230628_183458](https://github.com/GerbilSoft/rom-properties/assets/45115804/78867fc2-4120-46a1-bbaf-9661f6166ea7)

The games are fine, since Windows takes them well and displays the thumbnails correctly.

And on the other hand, when entering "kbuildsycoca5 --noincremental" it gives the following error: 
`kbuildsycoca5 running ....
kf.service.services: The desktop entry file "/usr/share/applications/org.freedesktop.Xwayland.desktop" has Type= "Application" but no Exec line
kf.service.sycoca: Invalid Service : "/usr/share/applications/org.freedesktop.Xwayland.desktop"`

**Comment by GerbilSoft** [comment]
The xattrs tab is a new feature being introduced in rom-properties v2.2.

Are you able to do a git bisect to figure out which commit broke this? (It seems to be working fine here.)

**Comment by Amnesia1000** [comment]
Sorry, it is an error that appeared on the PC of a friend when trying to install rom-properties, and until yesterday I was at home, before I left I uninstalled it so that it would not create problems. I currently use Gnome so I can not reproduce the problem.

Could it be because it has KDE plasma 5.27 and KDE 6?

**Comment by GerbilSoft** [comment]
I'm using KDE Plasma 5.27 on my own system, so that shouldn't be a problem.

KDE 6 isn't released yet. There's preliminary support for it, but I could see that potentially being an issue if some early KDE 6 packages are installed.

**Comment by Amnesia1000** [comment]
Sorry, I meant to say QT6 not KDE 6.

**Comment by GerbilSoft** [comment]
Qt6 is only used if the necessary KDE Frameworks 6 packages are found. If not, then it'll use Qt5, since that's what KF5 uses.

**Comment by Amnesia1000** [comment]
Ok, then I don't know what it could be, I installed it normally as I installed it before in KDE, you can close it if you want, if I ever travel again and I can give more information about the error I will do it without problem.

**Comment by dnmodder** [comment]
I have the same error and I am using Arch Linux + KDE Plasma 5.27.7, I checked that in Thunar it works well with 3DS ROMs but in Dolphin it doesn't.

I should add that I have installed the rom-properties package from the AUR, I am the current maintainer of the package.

**Comment by GerbilSoft** [comment]
This may be related to the changes to use the newer JSON plugin loading system introduced in KF5 5.89. I'll need to set up Manjaro and Arch VMs to see if I can reproduce it there.

EDIT: Here's an easy way to test. In `src/kde/kf5/CMakeLists.txt`, find the line that has this:

`SET(HAVE_JSON_PLUGIN_LOADER 1)`

and comment it out. (Add a `#` character at the beginning of the line.) Then rebuild and reinstall. (Remember to set `-DCMAKE_INSTALL_PREFIX=/usr` .)

**Comment by dnmodder** [comment]
Well I wanted to give it a try but now I have a compile error that has to do with gdkpixbuf and gtk4.
![imagen](https://github.com/GerbilSoft/rom-properties/assets/12377383/d207282e-2f35-4317-8ac1-9b5ef2bcdad0)

**Comment by dnmodder** [comment]
Ah, compiling from master does not give me the error.

**Comment by GerbilSoft** [comment]
That particular issue was fixed in commit 348adc1ba49b08c14346e977fcea4baf0fe13c0b and was caused by the GTK devs moving gdkpixbuf.h to deprecated in GTK 4.12.

I'll eventually need to replace GdkPixbuf with something else, but I'm not sure what.

**Comment by dnmodder** [comment]
I applied that patch to fix the build in the PKGBUILD and also the commenting out the line of code in CMakeLists.txt and the tab still doesn't show up in Dolphin with 3DS games.

**Comment by dnmodder** [comment]
I originally forgot to say that with Wii and Gamecube games I don't have that problem, only with 3DS ones.

**Comment by GerbilSoft** [comment]
What MIME type does Dolphin say the 3DS games are? (Also the `mimetype` command line tool, in case they differ.)

**Comment by dnmodder** [comment]
application/x-ctr-cci and application/x-nintendo-3ds-rom

**Comment by dnmodder** [comment]
xdg-mime query filetype tells me it is application/x-ctr-cci

**Comment by dnmodder** [comment]
Also, I have a 3DS (MiiMaker) .app file, it tells me that it is application/x-nintendo-3ds-ncch in Dolphin and with the xdg-mime command, with that ROM the ROM Properties tab is shown.

**Comment by dnmodder** [comment]
Another thing, if I change the .3ds extension to .app, the ROM Properties tab appears. And xdg-mime returns this: application/x-nintendo-3ds-rom

**Comment by GerbilSoft** [comment]
`application/x-ctr-cci` is the issue. This MIME type appears to be specific to Citra; both rom-properties and upstream shared-mime-info use `application/x-nintendo-3ds-rom`.

I'll add Citra's MIME types to rom-properties to improve support.

**Comment by dnmodder** [comment]
I thought removing the .3ds extension from there would fix it but no.
![imagen](https://github.com/GerbilSoft/rom-properties/assets/12377383/4853d34e-4534-42df-9341-5ef4edb12fcc)

**Comment by GerbilSoft** [comment]
Please try the latest commit from the master branch. Note that you will need to do a clean build because CMake doesn't easily let me add a dependency for the generated .desktop and .json files due to how it's generated.

Remember to run `kbuildsycoca5` after installing.

**Comment by dnmodder** [comment]
I confirm that it works correctly.
![imagen](https://github.com/GerbilSoft/rom-properties/assets/12377383/36f29bfe-e9ed-40d6-837d-2670ce181f9c)
![imagen](https://github.com/GerbilSoft/rom-properties/assets/12377383/94bcf4f1-b4f2-4607-8990-a7c8d643af41)

**Comment by dnmodder** [comment]
I have created a new package in AUR so that other users can test it.
https://aur.archlinux.org/packages/rom-properties-git
